const SEARCH_ENTITIES = 'SEARCH_ENTITIES';
const SEARCH_ASYNC_ENTITIES = 'SEARCH_ASYNC_ENTITIES';
const OPEN_MODAL = 'OPEN_MODAL';
const CLOSE_MODAL = 'CLOSE_MODAL';

export {
  SEARCH_ENTITIES,
  SEARCH_ASYNC_ENTITIES,
  OPEN_MODAL,
  CLOSE_MODAL,
};
